### ISSUE TITLE
OpenAPI ignores optional JSON parameters

### ISSUE THREAD

**Issue by PedroD** [derveloper/kotlin-openapi3-dsl#8]
https://stackoverflow.com/questions/61696873/why-isnt-swagger-detecting-optional-json-properties

**Comment by derveloper** [comment]
Hi,

thanks for pointing out, but I don't see where the DSL is the problem here.
I think this is jackson related.
My understanding is, if there is a non nullable type, jackson can't treat the property as optional because it  doen't know if there is a default value, it just sees non nullable and al clashing `required = false`.
The non nullable in this case wins over the `required = false`.

But this is just guessing, could you provide an example or a testcase where it behaves like you want it to?

Best,
Tristan

**Comment by PedroD** [comment]
Hello Tristan,

All the nullable properties in that example behave like intended (eg. `val medicalSpecialityId: Long? = null,`) because they are nullable, so OpenAPI accepts them as optional.

But if I change it to `val medicalSpecialityId: Long = 0L,`, I have no way to tell OpenAPI this parameter is optional (which makes sense, since despite it not being nullable, it has a default fallback value).

**Comment by derveloper** [comment]
Hi Pedro,

I don't think that the kotlin-openapi3-dsl is the problem here, all it does is constructing the swagger objects and for JSON output it is using the swagger provided mapper.
The DSL is just a thin wrapper around the OpenAPI models for easier construction via a DSL.
I have no clue on how this library here can fix this.
Maybe you should report this behavior to the swagger-core project here on github.

Best,
Tristan
